#ifndef FEATURE_ORDER_H
#define FEATURE_ORDER_H

typedef enum {
    FEAT_DESTINATION_PORT,
    FEAT_BWD_HEADER_LENGTH,
    FEAT_TOTAL_BACKWARD_PACKETS,
    FEAT_MIN_PACKET_LENGTH,
    FEAT_SUBFLOW_FWD_BYTES,
    FEAT_MAX_PACKET_LENGTH,
    FEAT_FLOW_DURATION,
    FEAT_FWD_PACKET_LENGTH_MAX,
    FEAT_BWD_PACKET_LENGTH_MAX,
    FEAT_MIN_SEG_SIZE_FORWARD,
    FEAT_FWD_HEADER_LENGTH,
    FEAT_PSH_FLAG_COUNT,
    FEAT_URG_FLAG_COUNT,
    FEAT_SYN_FLAG_COUNT,
    FEAT_ACK_FLAG_COUNT,
    FEAT_FIN_FLAG_COUNT,
    FEAT_RST_FLAG_COUNT,
    NUM_FEATURES = 17
} FeatureIndex;

#endif